### ISSUE TITLE
ep_real_time_chat breaks my etherpad instance

### ISSUE THREAD

**Issue by meaz** [ether/ep_real_time_chat#5]
I use etherpad 1.8.6 and ep_real_time_chat.
I recently updated ep_real_time_chat. And it broke my instance: when I open a pad, I have "Loading" instead of the welcome page. ANd if I check the Firefox console, I see this:
```
jQuery.Deferred exception: assignment to undeclared variable temp getParam@http://myip:9001/static/js/require-kernel.js?v=5488f433 line 226 > Function:116:22
ep_real_time_chat/static/js/main.js/exports.postAceInit@http://myip:9001/static/js/require-kernel.js?v=5488f433 line 226 > Function:8:46
normalizedhook@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:12252:27
hookCallWrapper@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:12258:14
ep_etherpad-lite/static/js/pluginfw/hooks.js/exports.callAll/<@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:12312:12
underscore/underscore.js/</_.collect@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:10634:24
ep_etherpad-lite/static/js/pluginfw/hooks.js/exports.callAll@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:12311:22
Ace2Inner/this.init/<@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:5345:13
mightThrow@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:3912:29
resolve/</process<@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:3980:12
 undefined
```
As soon as I remove the plugin, the problem is gone.

**Comment by JohnMcLear** [comment]
ugh confirmed.  fixing now.

**Comment by JohnMcLear** [comment]
Fixed and published.  Sorry about that :)

**Comment by meaz** [comment]
that was fast, thanks!

**Comment by JohnMcLear** [comment]
yw

**Comment by meaz** [comment]
I'm sorry to tell you that I still have the issue with this in the console:
```
jQuery.Deferred exception: assignment to undeclared variable temp getParam@http://myip:9001/static/js/require-kernel.js?v=17ffe363 line 226 > Function:116:22
ep_real_time_chat/static/js/main.js/exports.postAceInit@http://myip:9001/static/js/require-kernel.js?v=17ffe363 line 226 > Function:8:46
normalizedhook@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:12252:27
hookCallWrapper@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:12258:14
ep_etherpad-lite/static/js/pluginfw/hooks.js/exports.callAll/<@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:12312:12
underscore/underscore.js/</_.collect@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:10634:24
ep_etherpad-lite/static/js/pluginfw/hooks.js/exports.callAll@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:12311:22
Ace2Inner/this.init/<@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:5345:13
mightThrow@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:3912:29
resolve/</process<@http://myip:9001/p/5k6ZXPnxd3gMR6N5fNcN line 24 > scriptElement line 241 > Function:3980:12
```

**Comment by JohnMcLear** [comment]
Are you up to 0.2.8?  npm cache can take a while to update..

**Comment by meaz** [comment]
yes I am

**Comment by JohnMcLear** [comment]
And did you clear your browser cache for the pad? 👍

**Comment by meaz** [comment]
Thanks, that was it. Sorry for not thinking about it...

**Comment by JohnMcLear** [comment]
:D it's cool it happens a lot..  Enjoy!
